# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Require Python 3.7 or later
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/PyCQA/flake8
    rev: v5.0.4
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/bandit
    rev: v1.7.1
    hooks:
    -   id: bandit
-   repo: https://github.com/PyCQA/pydocstyle
    rev: v6.3.0
    hooks:
    -   id: pydocstyle
-   repo: https://github.com/PyCQA/isort
    rev: v5.11.3
    hooks:
    -   id: isort
-   repo: https://github.com/adamchainz/django-upgrade
    rev: v1.0.0
    hooks:
    -   id: django-upgrade
-   repo: https://github.com/dannysepler/rm_unneeded_f_str
    rev: v0.2.0
    hooks:
    -   id: rm-unneeded-f-str
